version: "3"
volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  
  
  
  next:
    image: nextjs-docker
    ports: 
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgrespw@postgres:5432
    depends_on: 
      - postgres